apiVersion: v1
kind: PersistentVolume
metadata:
  name: caichat-pv-ollama
  labels:
    type: local
    {{- include "caichat.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: "/mnt/data/caichat-pv-ollama"
