apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-volume-claim
  labels:
    {{- include "caichat.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
